/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minav1.gui;

/**
 *
 * @author aleks
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuGrad = new javax.swing.JMenu();
        menuGradItemDodaj = new javax.swing.JMenuItem();
        menuGradItemObrisi = new javax.swing.JMenuItem();
        menuGradItemGradoviDefault = new javax.swing.JMenuItem();
        menuGradItemGradoviCustom = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuGrad.setText("Grad");

        menuGradItemDodaj.setText("Dodaj");
        menuGradItemDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGradItemDodajActionPerformed(evt);
            }
        });
        menuGrad.add(menuGradItemDodaj);

        menuGradItemObrisi.setText("Obrisi");
        menuGradItemObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGradItemObrisiActionPerformed(evt);
            }
        });
        menuGrad.add(menuGradItemObrisi);

        menuGradItemGradoviDefault.setText("Gradovi Default");
        menuGrad.add(menuGradItemGradoviDefault);

        menuGradItemGradoviCustom.setText("Gradovi Custom");
        menuGrad.add(menuGradItemGradoviCustom);

        jMenuBar1.add(menuGrad);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGradItemDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGradItemDodajActionPerformed
        // TODO add your handling code here:
        
        new DodajGrad(this, true).setVisible(true);
        
    }//GEN-LAST:event_menuGradItemDodajActionPerformed

    private void menuGradItemObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGradItemObrisiActionPerformed

        new IzbrisiGrad(this, true).setVisible(true);
        
    }//GEN-LAST:event_menuGradItemObrisiActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuGrad;
    private javax.swing.JMenuItem menuGradItemDodaj;
    private javax.swing.JMenuItem menuGradItemGradoviCustom;
    private javax.swing.JMenuItem menuGradItemGradoviDefault;
    private javax.swing.JMenuItem menuGradItemObrisi;
    // End of variables declaration//GEN-END:variables
}
